{% set name = "openai" %}
{% set version = "0.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d71c0fc1b5f3df0f41875f40c8449a96fd6e55775c601ffc206f5b72ae4cad57

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    - requests >=2.20
    - tqdm

test:
  imports:
    - openai
    - openai.api_resources
  commands:
    - pip check
    - openai api -h
  requires:
    - pip

about:
  home: https://beta.openai.com
  summary: Python client library for the OpenAI API
  description: |
    The OpenAI Python library provides convenient access to the OpenAI API
    from applications written in the Python language.
    It includes a pre-defined set of classes for API resources that initialize
    themselves dynamically from API responses which makes it compatible with
    a wide range of versions of the OpenAI API.

    This library additionally provides an `openai` command-line utility which
    makes it easy to interact with the API from your terminal.
    Run `openai api -h` for usage.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://beta.openai.com/docs/api-reference?lang=python
  dev_url: https://github.com/openai/openai-python

extra:
  recipe-maintainers:
    - BastianZim
