{% set name = "openai" %}
{% set version = "1.59.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openai/openai-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4265573a8a5ee7ff149e466ddf5a52e9229109b8784f1dbac7aaca749e1f9cef

build:
  number: 0
  noarch: python
  entry_points:
    - openai=openai.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
    - python {{ python_min }}
  run:
    - typing_extensions >=4.11,<5
    - jiter >=0.4.0,<1
    - sniffio
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing-extensions >=4.11,<5
    - python >={{ python_min }}
    - tqdm >4

test:
  imports:
    - openai
  commands:
    - openai api -h
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://beta.openai.com
  summary: Python client library for the OpenAI API
  description: |
    The OpenAI Python library provides convenient access to the OpenAI API
    from applications written in the Python language.
    It includes a pre-defined set of classes for API resources that initialize
    themselves dynamically from API responses which makes it compatible with
    a wide range of versions of the OpenAI API.

    This library additionally provides an `openai` command-line utility which
    makes it easy to interact with the API from your terminal.
    Run `openai api -h` for usage.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://platform.openai.com/docs/api-reference?lang=python
  dev_url: https://github.com/openai/openai-python

extra:
  recipe-maintainers:
    - BastianZim
