{% set name = "openai" %}
{% set version = "0.22.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openai/openai-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 06a07f0aa96dfd4e97b4de50e05cc079503061c9b70876aa45eed126b2f00d1f

build:
  number: 0
  noarch: python
  entry_points:
    - openai=openai._openai_scripts:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.22.0
    - openpyxl >=3.0.7
    - pandas >=1.2.3
    - pandas-stubs >=1.1.0.11
    - python >=3.7
    - requests >=2.20
    - tqdm
    - colorama
    # Because of some error with tqdm. Should be checked again some time down the road.

test:
  imports:
    - openai
    - openai.api_resources
  commands:
    - openai api -h
    - pip check
  requires:
    - pip

about:
  home: https://beta.openai.com
  summary: Python client library for the OpenAI API
  description: |
    The OpenAI Python library provides convenient access to the OpenAI API
    from applications written in the Python language.
    It includes a pre-defined set of classes for API resources that initialize
    themselves dynamically from API responses which makes it compatible with
    a wide range of versions of the OpenAI API.

    This library additionally provides an `openai` command-line utility which
    makes it easy to interact with the API from your terminal.
    Run `openai api -h` for usage.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://beta.openai.com/docs/api-reference?lang=python
  dev_url: https://github.com/openai/openai-python

extra:
  recipe-maintainers:
    - BastianZim
